### ISSUE TITLE
Revamp string construction now that its more complicated

### ISSUE THREAD

**Issue by timkpaine** [timkpaine/pyEX#51]
stop doing string addition and use format strings now that the apis have more fields and params

**Comment by Jacob-Charles-Killian** [comment]
This sounds like the type of thing I could help with.  I've coded since gwbasic, with turbo pascal, *nix shell, perl, php, c#, and a host of other languages in between.  I'm relatively new to Python (and sometimes forget to pay attention to interpreter version).  The other problem I need to overcome is that all of my coding has been scripting in support of system/network administration.  I'm new to team-coding.  I am just now joining the open source community and have a lot to learn about how to do things.  I've been looking for a project to help with so I can start learning git and about how people build off of other people's code.  This one seems likeable for a variety of reasons.  I started a repository of basic data-structures and algorithms (linked-lists, binary-trees, heaps, etc.), but I really need to be working on a project with other people to learn modern collaborative coding practices.

Since I'm graduating with a bachelor's in Data Analytics I was looking for a timeseries data stream to start building predictive models off of.  I came across IEX Cloud and really appreciated their sandbox option.  That led me to this project.

I like that this project is relative small, but active.  I like the wrapper so far, and I think it will suit my needs for a few different timeseries predictive models.  My girlfriend paid for grad school with the stock market.  I'd like to do the same, but I want to use more than her intuition and her dad's "system".

I hope you'll accept me into this project and assign me some tasks.

**Comment by westonplatter** [comment]
@timkpaine I see this issue was created/filed a while ago. I have a few methods I use that I'd like to customize with params (eg, `pyEX.stocks.intradayDF('aapl', token=my_token, version='v1')` with `chartIEXOnly=1`. docs = https://iexcloud.io/docs/api/#intraday-prices).

Do you have a pattern in place that I could start implementing? If not, happy to draft something up for feedback.

**Comment by timkpaine** [comment]
No existing pattern, this issue is basically "come up with a pattern". Happy to provide feedback and help

**Comment by westonplatter** [comment]
Cool. I'll see what I can do.

**Comment by westonplatter** [comment]
Wanted to circle back with a possible pattern for passing http query params, https://github.com/westonplatter/pyEX/commit/0b5a446c4f1908ab4dbbe34c0631ef98614af4d4. 

I implemented the pattern within 
- `pyEX.stocks.intraday`
- `pyEX.stocks.intradayDF`

To kick the tires, this executes the code pattern,
```
params = {"chartSimplify": 1}
data = pyEX.stocks.intraday('AAPL', token=environ["IEX"], version='v1', params=params)
```

**Comment by timkpaine** [comment]
looks fine

**Comment by westonplatter** [comment]
@timkpaine cool. I'll start revamping the methods. For the sake of incremental changes + testability, I'll plan to create an `old` and `new` json fetching methods.

**Comment by timkpaine** [comment]
happening incrementally as methods get worked on
