### ISSUE TITLE
How to retrieve the monthly data by chartDF?

### ISSUE THREAD

**Issue by pivdets** [timkpaine/pyEX#94]
To plot a daily K-line, we could use

```
ticker = 'AMD'
timeframe = '3m'
token = 'XXXX'
c = p.client.Client(token)
df = c.chartDF(ticker, timeframe)
df = df[['close']]
df.reset_index(level=0, inplace=True)
df.columns=['ds','y']
plt.plot(df.ds, df.y, label='AMD')
plt.show()
```

I was wondering how to plot the monthly K-line? I mean, each spot of the x-axis is the last day of the month.

**Comment by timkpaine** [comment]
I think this is more of a pandas question rather than an IEX question, so i'm closing the issue (but happy to continue discussing here and put any functionality into https://github.com/timkpaine/pyEX-studies)

Here is just some quick hacking dropping the day from the date time index and then grouping by the month:
<img width="711" alt="Screen Shot 2020-01-26 at 9 20 14 AM" src="https://user-images.githubusercontent.com/3105306/73136570-104e0800-401d-11ea-9c73-b8045eeaa11e.png">

**Comment by timkpaine** [comment]
https://github.com/timkpaine/pyEX-studies/issues/10
